on: pull_request

name: Move Issue to Code Review

jobs:
  move-to-code-review:
    name: Move to Code Review
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Find in commit messages
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits

    - name: Transition ticket
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "CODE REVIEW (ON GITHUB)"

    - name: Comment on ticket
      uses: atlassian/gajira-comment@master
      with:
        issue: ${{ steps.find.outputs.issue }}
        comment: github.com/${{GITHUB_REPOSITORY}}/commit/${{GITHUB_SHA}}
  