on:
  pull_request:
    types: [closed]

name: Merge and resolve Jira issue

jobs:
  jira:
    name: Merge and resolve Jira issue
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Transit Jira issue
      uses: Timmatt-Lee/Github-Jira-Integration@master
      with:
        host: ${{ secrets.JIRA_BASE_URL }}
        email: ${{ secrets.JIRA_USER_EMAIL }}
        token: ${{ secrets.JIRA_API_TOKEN }}
        project: "Canvas"
        transition: "Testing"
        isOnlyTransition: true